GET http://localhost:3003/api/blogs/

####
GET http://localhost:3003/api/blogs/68eb4696bb54723f00cd023f

####
DELETE http://localhost:3003/api/blogs/68eb4696bb54723f00cd023f

####
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "test update title",
    "author": "test update author",
    "url": "test update url",
    "likes": 500
}

####
PUT http://localhost:3003/api/blogs/68ea0f2e6e84085fcb7be897
Content-Type: application/json

{
    "title": "title 1",
    "author": "author 1",
    "url": "url 1",
    "likes": 100
}